import '../../../../styles/globals.css'

export const metadata = {
  title: 'Jungles of Dorado',
  description: 'Generated by create next app',
  icons:{
    icon: '/favicon.ico'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
